version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=laravel
      - PMA_PASSWORD=secret
    depends_on:
      - database

volumes:
  db-data: ~
